name=Adafruit TMF8806
version=1.0.0
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=Arduino library for the TMF8806 Time-of-Flight distance sensor.
paragraph=Arduino library for the TMF8806 dToF sensor from ams-OSRAM. Measures distances from 10mm to 5000mm.
category=Sensors
url=https://github.com/adafruit/Adafruit_TMF8806
architectures=*
depends=Adafruit BusIO
